### ISSUE TITLE
Everit lib isn't reading files from classpath

### ISSUE THREAD

**Issue by takabayashi** [marvin-ai/marvin-engine-executor#43]
To reference inner schema files is necessary to use the #ref attribute. But default URL Handler can not be used without a valid protocol (Eg. http or file) and an absolute path.

this [commit](https://github.com/marvin-ai/marvin-engine-executor/pull/40/commits/286892f642c0fed37260fed3b60dcc349da7c605) is disabling this validation...just a temporary way to skip the problem once the bug is breaking our build...

for a #ref like "/EngineActionSchema.json" the exception launched is:  

> Exception in thread "main" java.io.UncheckedIOException: java.net.MalformedURLException: no protocol: /EngineActionSchema.json
> 	at org.everit.json.schema.loader.internal.DefaultSchemaClient.get(DefaultSchemaClient.java:35)
> 	at org.everit.json.schema.loader.internal.JSONPointer.executeWith(JSONPointer.java:81)
> 	at org.everit.json.schema.loader.internal.JSONPointer.lambda$forURL$1(JSONPointer.java:133)
> 	at org.everit.json.schema.loader.internal.JSONPointer.query(JSONPointer.java:152)
> 	at org.everit.json.schema.loader.ReferenceLookup.lookup(ReferenceLookup.java:99)
> 	at org.everit.json.schema.loader.SchemaLoader.buildSchemaWithoutExplicitType(SchemaLoader.java:253)
> 	at org.everit.json.schema.loader.SchemaLoader.lambda$load$0(SchemaLoader.java:290)
> 	at java.util.Optional.orElseGet(Optional.java:267)
> 	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:288)
> 	at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:346)
> 	at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$addPropertySchemaDefinition$4(ObjectSchemaLoader.java:79)
> 	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer$IdModifyingTypeConsumerImpl.lambda$then$0(TypeBasedMultiplexer.java:78)
> 	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.orElse(TypeBasedMultiplexer.java:233)
> 	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.requireAny(TypeBasedMultiplexer.java:243)
> 	at org.everit.json.schema.loader.ObjectSchemaLoader.addPropertySchemaDefinition(ObjectSchemaLoader.java:81)
> 	at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$populatePropertySchemas$3(ObjectSchemaLoader.java:70)
> 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
> 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
> 	at org.everit.json.schema.loader.ObjectSchemaLoader.populatePropertySchemas(ObjectSchemaLoader.java:69)
> 	at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$load$0(ObjectSchemaLoader.java:34)
> 	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer$IdModifyingTypeConsumerImpl.lambda$then$0(TypeBasedMultiplexer.java:78)
> 	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.orElse(TypeBasedMultiplexer.java:233)
> 	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.requireAny(TypeBasedMultiplexer.java:243)
> 	at org.everit.json.schema.loader.ObjectSchemaLoader.load(ObjectSchemaLoader.java:35)
> 	at org.everit.json.schema.loader.SchemaLoader.buildObjectSchema(SchemaLoader.java:324)
> 	at org.everit.json.schema.loader.SchemaLoader.loadForExplicitType(SchemaLoader.java:317)
> 	at org.everit.json.schema.loader.SchemaLoader.loadForType(SchemaLoader.java:335)
> 	at org.everit.json.schema.loader.SchemaLoader.lambda$load$0(SchemaLoader.java:292)
> 	at java.util.Optional.orElseGet(Optional.java:267)
> 	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:288)
> 	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:178)
> 	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:163)
> 	at org.marvin.util.JsonUtil$.validateJson(JsonUtil.scala:67)
> 	at org.marvin.util.JsonUtil$.fromJson(JsonUtil.scala:48)
> 	at org.marvin.executor.api.GenericHttpAPI.$anonfun$readJsonIfFileExists$1(GenericHttpAPI.scala:276)
> 	at scala.util.Try$.apply(Try.scala:209)
> 	at org.marvin.executor.api.GenericHttpAPI.readJsonIfFileExists(GenericHttpAPI.scala:276)
> 	at org.marvin.executor.api.GenericHttpAPI.setupSystem(GenericHttpAPI.scala:234)
> 	at org.marvin.executor.api.GenericHttpAPI.setupSystem$(GenericHttpAPI.scala:233)
> 	at org.marvin.executor.api.GenericHttpAPIImpl.setupSystem(GenericHttpAPI.scala:53)
> 	at org.marvin.executor.api.GenericHttpAPI$.main(GenericHttpAPI.scala:224)
> 	at org.marvin.executor.api.GenericHttpAPI.main(GenericHttpAPI.scala)
> Caused by: java.net.MalformedURLException: no protocol: /EngineActionSchema.json
> 	at java.net.URL.<init>(URL.java:593)
> 	at java.net.URL.<init>(URL.java:490)
> 	at java.net.URL.<init>(URL.java:439)
> 	at org.everit.json.schema.loader.internal.DefaultSchemaClient.get(DefaultSchemaClient.java:33)
> 	... 41 more

for a #ref with a valid protocol like "file:///EngineActionSchema.json" the exception launched is:  

> Exception in thread "main" java.io.UncheckedIOException: java.io.FileNotFoundException: /EngineActionSchema.json (No such file or directory)
> 	at org.everit.json.schema.loader.internal.DefaultSchemaClient.get(DefaultSchemaClient.java:35)
> 	at org.everit.json.schema.loader.internal.JSONPointer.executeWith(JSONPointer.java:81)
> 	at org.everit.json.schema.loader.internal.JSONPointer.lambda$forURL$1(JSONPointer.java:133)
> 	at org.everit.json.schema.loader.internal.JSONPointer.query(JSONPointer.java:152)
> 	at org.everit.json.schema.loader.ReferenceLookup.lookup(ReferenceLookup.java:99)
> 	at org.everit.json.schema.loader.SchemaLoader.buildSchemaWithoutExplicitType(SchemaLoader.java:253)
> 	at org.everit.json.schema.loader.SchemaLoader.lambda$load$0(SchemaLoader.java:290)
> 	at java.util.Optional.orElseGet(Optional.java:267)
> 	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:288)
> 	at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:346)
> 	at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$addPropertySchemaDefinition$4(ObjectSchemaLoader.java:79)
> 	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer$IdModifyingTypeConsumerImpl.lambda$then$0(TypeBasedMultiplexer.java:78)
> 	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.orElse(TypeBasedMultiplexer.java:233)
> 	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.requireAny(TypeBasedMultiplexer.java:243)
> 	at org.everit.json.schema.loader.ObjectSchemaLoader.addPropertySchemaDefinition(ObjectSchemaLoader.java:81)
> 	at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$populatePropertySchemas$3(ObjectSchemaLoader.java:70)
> 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
> 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
> 	at org.everit.json.schema.loader.ObjectSchemaLoader.populatePropertySchemas(ObjectSchemaLoader.java:69)
> 	at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$load$0(ObjectSchemaLoader.java:34)
> 	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer$IdModifyingTypeConsumerImpl.lambda$then$0(TypeBasedMultiplexer.java:78)
> 	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.orElse(TypeBasedMultiplexer.java:233)
> 	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.requireAny(TypeBasedMultiplexer.java:243)
> 	at org.everit.json.schema.loader.ObjectSchemaLoader.load(ObjectSchemaLoader.java:35)
> 	at org.everit.json.schema.loader.SchemaLoader.buildObjectSchema(SchemaLoader.java:324)
> 	at org.everit.json.schema.loader.SchemaLoader.loadForExplicitType(SchemaLoader.java:317)
> 	at org.everit.json.schema.loader.SchemaLoader.loadForType(SchemaLoader.java:335)
> 	at org.everit.json.schema.loader.SchemaLoader.lambda$load$0(SchemaLoader.java:292)
> 	at java.util.Optional.orElseGet(Optional.java:267)
> 	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:288)
> 	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:178)
> 	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:163)
> 	at org.marvin.util.JsonUtil$.validateJson(JsonUtil.scala:67)
> 	at org.marvin.util.JsonUtil$.fromJson(JsonUtil.scala:48)
> 	at org.marvin.executor.api.GenericHttpAPI.$anonfun$readJsonIfFileExists$1(GenericHttpAPI.scala:276)
> 	at scala.util.Try$.apply(Try.scala:209)
> 	at org.marvin.executor.api.GenericHttpAPI.readJsonIfFileExists(GenericHttpAPI.scala:276)
> 	at org.marvin.executor.api.GenericHttpAPI.setupSystem(GenericHttpAPI.scala:234)
> 	at org.marvin.executor.api.GenericHttpAPI.setupSystem$(GenericHttpAPI.scala:233)
> 	at org.marvin.executor.api.GenericHttpAPIImpl.setupSystem(GenericHttpAPI.scala:53)
> 	at org.marvin.executor.api.GenericHttpAPI$.main(GenericHttpAPI.scala:224)
> 	at org.marvin.executor.api.GenericHttpAPI.main(GenericHttpAPI.scala)
> Caused by: java.io.FileNotFoundException: /EngineActionSchema.json (No such file or directory)
> 	at java.io.FileInputStream.open0(Native Method)
> 	at java.io.FileInputStream.open(FileInputStream.java:195)
> 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
> 	at java.io.FileInputStream.<init>(FileInputStream.java:93)
> 	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
> 	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
> 	at java.net.URLConnection.getContent(URLConnection.java:739)
> 	at java.net.URL.getContent(URL.java:1059)
> 	at org.everit.json.schema.loader.internal.DefaultSchemaClient.get(DefaultSchemaClient.java:33)
> 	... 41 more

**Comment by takabayashi** [comment]
googling in a fast way I found this [solution](https://stackoverflow.com/questions/861500/url-to-load-resources-from-the-classpath-in-java ) referred by this [thread](https://github.com/everit-org/json-schema/issues/47).

I think is a very good first try....

**Comment by takabayashi** [comment]
fixed by @oldfly with PR #46 already merged!
