### ISSUE TITLE
Persisting model error with checksum

### ISSUE THREAD

**Issue by viniciusvg** [marvin-ai/marvin-engine-executor#64]
In the log file:

[INFO] [03/06/2018 16:23:45.049] [af_scoring_model-akka.actor.default-dispatcher-15] [akka://af_scoring_model/user/pipelineActor/artifactSaver] Copying files from /marv
in-data/.artifacts/af_scoring_model/model to /tmp/marvin/af_scoring_model/v0.0.1/model/pipeline_c0c356ca-2252-49c2-8683-17f132eac6c0
392704 [af_scoring_model-akka.actor.default-dispatcher-15] INFO  org.apache.hadoop.fs.FSInputChecker  - Found checksum error: b[0, 4096]=785eecbd8757145db7ee8b39a1a8982
3e69cb3d2d0dd556d78cd01b302022a8a20c19c3020411014101505143180080650498e31e73f769fb5aa57552155ecf73be78c7bcf3ee7b247edf773758595abd66f3d73ceecbeb7d243e6c70
...
org.apache.hadoop.fs.ChecksumException: Checksum error: file:/marvin-data/.artifacts/af_scoring_model/model at 0 exp: 504017920 got: -1631345060
        at org.apache.hadoop.fs.FSInputChecker.verifySums(FSInputChecker.java:323)
        at org.apache.hadoop.fs.FSInputChecker.readChecksumChunk(FSInputChecker.java:279)
        at org.apache.hadoop.fs.FSInputChecker.read1(FSInputChecker.java:228)
        at org.apache.hadoop.fs.FSInputChecker.read(FSInputChecker.java:196)
        at java.io.DataInputStream.read(DataInputStream.java:100)
        at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:86)
        at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:60)
        at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:120)
        at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:366)
        at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:338)
        at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:1969)
        at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:1937)
        at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:1902)
        at org.marvin.artifact.manager.ArtifactHdfsSaver$$anonfun$receive$1.applyOrElse(ArtifactHdfsSaver.scala:84)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at org.marvin.artifact.manager.ArtifactHdfsSaver.aroundReceive(ArtifactHdfsSaver.scala:28)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
        at akka.actor.ActorCell.invoke(ActorCell.scala:496)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[INFO] [03/06/2018 16:23:47.542] [af_scoring_model-akka.actor.default-dispatcher-13] [akka://af_scoring_model/user/pipelineActor/evaluatorActor] Reload remote procedure to evaluator Done with [Reloaded]. Protocol [pipeline_c0c356ca
-2252-49c2-8683-17f132eac6c0].
[INFO] [03/06/2018 16:23:47.543] [af_scoring_model-akka.actor.default-dispatcher-13] [akka://af_scoring_model/user/pipelineActor/evaluatorActor] Start the execute remote procedure to evaluator. Protocol [pipeline_c0c356ca-2252-49c2
-8683-17f132eac6c0]
[INFO] [03/06/2018 16:23:47.766] [af_scoring_model-akka.actor.default-dispatcher-13] [akka://af_scoring_model/user/pipelineActor/evaluatorActor] Execute remote procedure to evaluator Done with [Done]. Protocol [pipeline_c0c356ca-22
52-49c2-8683-17f132eac6c0]
[ERROR] [03/06/2018 16:23:47.773] [af_scoring_model-akka.actor.default-dispatcher-11] [akka://af_scoring_model/user/pipelineActor/artifactSaver] Checksum error: file:/marvin-data/.artifacts/af_scoring_model/model at 0 exp: 50401792
0 got: -1631345060
org.apache.hadoop.fs.ChecksumException: Checksum error: file:/marvin-data/.artifacts/af_scoring_model/model at 0 exp: 504017920 got: -1631345060
        at org.apache.hadoop.fs.FSInputChecker.verifySums(FSInputChecker.java:323)
        at org.apache.hadoop.fs.FSInputChecker.readChecksumChunk(FSInputChecker.java:279)
        at org.apache.hadoop.fs.FSInputChecker.read1(FSInputChecker.java:228)
        at org.apache.hadoop.fs.FSInputChecker.read(FSInputChecker.java:196)
        at java.io.DataInputStream.read(DataInputStream.java:100)
        at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:86)
        at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:60)
        at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:120)
        at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:366)
        at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:338)
        at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:1969)
        at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:1937)
        at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:1902)
        at org.marvin.artifact.manager.ArtifactHdfsSaver$$anonfun$receive$1.applyOrElse(ArtifactHdfsSaver.scala:84)

Request pipeline status: returned finished.
"{\"actionName\":\"pipeline\",\"protocol\":\"pipeline_c0c356ca-2252-49c2-8683-17f132eac6c0\",\"datetime\":{\"year\":2018,\"monthValue\":3,\"hour\":16,\"minute\":23,\"second\":47,\"nano\":767000000,\"dayOfYear\":65,\"dayOfWeek\":\"TUESDAY\",\"month\":\"MARCH\",\"dayOfMonth\":6,\"chronology\":{\"calendarType\":\"iso8601\",\"id\":\"ISO\"}},\"status\":{\"name\":\"finished\",\"code\":1},\"formattedDatetime\":\"03/06/2018 16:23:47\"}"

**Comment by viniciusvg** [comment]
The error occurred because there were a .model.crc file in the artifacts folder.

Removing the file solved the problem.
